-- schema.sql
-- SQLite Database schema for Ownership Intelligence Platform (Phase 1)

-- Pipeline executions track the run status of the overall pipeline
CREATE TABLE IF NOT EXISTS pipeline_executions (
    execution_id TEXT PRIMARY KEY,
    status TEXT NOT NULL CHECK(status IN ('Pending', 'Running', 'Completed', 'Failed', 'Cancelled')),
    started_at DATETIME NOT NULL,
    finished_at DATETIME,
    error_message TEXT
);

-- Job executions track individual agents inside a pipeline run
CREATE TABLE IF NOT EXISTS job_executions (
    job_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL,
    agent_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('Pending', 'Running', 'Retrying', 'Completed', 'Failed', 'Cancelled')),
    run_number INTEGER NOT NULL DEFAULT 1,
    started_at DATETIME NOT NULL,
    finished_at DATETIME,
    duration_seconds REAL,
    input_hash TEXT,
    output_hash TEXT,
    results TEXT, -- JSON string containing the final output payload
    metrics TEXT, -- JSON string containing records_processed, output_size, etc.
    error_message TEXT,
    FOREIGN KEY(execution_id) REFERENCES pipeline_executions(execution_id)
);

-- Evidence records store the Data Provenance trail for institutional auditing
CREATE TABLE IF NOT EXISTS evidence_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id TEXT NOT NULL,
    company_uuid TEXT,
    field_name TEXT NOT NULL,
    value TEXT NOT NULL,
    source TEXT NOT NULL,
    source_doc_link TEXT,
    file_hash TEXT,
    confidence_score REAL,
    quarter TEXT,
    timestamp DATETIME NOT NULL,
    FOREIGN KEY(job_id) REFERENCES job_executions(job_id)
);

-- Audit logs record fine-grained internal steps of agents for full auditability
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id TEXT NOT NULL,
    step TEXT NOT NULL,
    action TEXT NOT NULL,
    timestamp DATETIME NOT NULL,
    metadata TEXT, -- JSON string containing additional properties
    FOREIGN KEY(job_id) REFERENCES job_executions(job_id)
);

-- Companies table stores the master details of all companies in the NSE universe
CREATE TABLE IF NOT EXISTS companies (
    company_uuid TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    isin TEXT NOT NULL,
    name TEXT NOT NULL,
    exchange TEXT NOT NULL DEFAULT 'NSE',
    status TEXT NOT NULL CHECK(status IN ('Active', 'Delisted')) DEFAULT 'Active',
    listing_date TEXT,
    delisting_date TEXT,
    series TEXT,
    face_value REAL,
    market_segment TEXT,
    registered_office TEXT,
    website TEXT,
    cin TEXT,
    last_updated TEXT NOT NULL,
    source TEXT NOT NULL,
    source_version TEXT,
    UNIQUE(symbol),
    UNIQUE(isin)
);

-- Company history tracks changes to critical fields (symbol, name, isin)
CREATE TABLE IF NOT EXISTS company_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    field_name TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    change_date TEXT NOT NULL,
    reason TEXT,
    execution_id TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Universe snapshots store metadata about the company universe version generated by each execution
CREATE TABLE IF NOT EXISTS universe_snapshots (
    snapshot_id TEXT PRIMARY KEY,
    version TEXT NOT NULL UNIQUE,
    execution_id TEXT NOT NULL,
    company_count INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY(execution_id) REFERENCES pipeline_executions(execution_id)
);

-- Company profiles store enriched corporate profiles and metadata in a versioned structure
CREATE TABLE IF NOT EXISTS company_profiles (
    profile_uuid TEXT PRIMARY KEY,
    company_uuid TEXT NOT NULL,
    version TEXT NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    business_description TEXT,
    industry TEXT,
    sector TEXT,
    website TEXT,
    headquarters TEXT,
    products TEXT,       -- JSON string (list of core products)
    services TEXT,       -- JSON string (list of core services)
    management TEXT,     -- JSON string (list of officers/executives)
    market_cap REAL,
    employee_count INTEGER,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Promoter holdings raw records
CREATE TABLE IF NOT EXISTS promoter_holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    promoter_holding_pct REAL NOT NULL,
    promoter_group_holding_pct REAL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- FII (Foreign Institutional Investor) holdings raw records
CREATE TABLE IF NOT EXISTS fii_holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    fii_holding_pct REAL NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- DII (Domestic Institutional Investor) holdings raw records
CREATE TABLE IF NOT EXISTS dii_holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    dii_holding_pct REAL NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Mutual Fund holdings raw records (typically a subset of DII)
CREATE TABLE IF NOT EXISTS mutual_fund_holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    mf_holding_pct REAL NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Public / Retail holdings raw records
CREATE TABLE IF NOT EXISTS public_holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    public_holding_pct REAL NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Promoter pledge raw records (pledged shares as a % of promoter's holding)
CREATE TABLE IF NOT EXISTS promoter_pledges (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    pledged_pct REAL NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Unified quarterly ownership snapshots (single source of truth)
CREATE TABLE IF NOT EXISTS ownership_snapshots (
    snapshot_uuid TEXT PRIMARY KEY,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    version TEXT NOT NULL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    promoter_holding_pct REAL NOT NULL,
    fii_holding_pct REAL NOT NULL,
    dii_holding_pct REAL NOT NULL,
    mf_holding_pct REAL NOT NULL,
    public_holding_pct REAL NOT NULL,
    pledged_pct REAL NOT NULL,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Quarterly company-level analytics (deltas)
CREATE TABLE IF NOT EXISTS company_quarterly_analytics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_uuid TEXT NOT NULL,
    quarter TEXT NOT NULL,
    promoter_delta REAL,
    fii_delta REAL,
    dii_delta REAL,
    mf_delta REAL,
    pledged_delta REAL,
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    source TEXT NOT NULL,
    FOREIGN KEY(company_uuid) REFERENCES companies(company_uuid)
);

-- Consolidated ranking reports (JSON reports of Top buying/reduction companies)
CREATE TABLE IF NOT EXISTS analytics_reports (
    report_uuid TEXT PRIMARY KEY,
    quarter TEXT NOT NULL,
    report_type TEXT NOT NULL,
    report_data TEXT NOT NULL, -- JSON string
    is_current INTEGER NOT NULL CHECK(is_current IN (0, 1)) DEFAULT 1,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL
);

-- Active trades table to track opened positions, targets, and exit alerts
CREATE TABLE IF NOT EXISTS active_trades (
    trade_id TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    entry_quarter TEXT NOT NULL,
    entry_price REAL NOT NULL,
    current_price REAL NOT NULL,
    target_price_10 REAL NOT NULL,
    target_price_20 REAL NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('Open', 'Closed')) DEFAULT 'Open',
    entry_date TEXT NOT NULL,
    exit_date TEXT,
    exit_price REAL,
    exit_reason TEXT CHECK(exit_reason IN ('Target 10 Hit', 'Target 20 Hit', 'Promoter Sell', 'Time Stop')),
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    FOREIGN KEY(symbol) REFERENCES companies(symbol)
);
